OneCard.MVC/Controllers/BooksController.cs
using SmartMvc.Core.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OneCard.MVC.Controllers
{
    public class BooksController : GlobalController
    {
        
        public ActionResult Index()
        {
            AddModelSuccess();
            return View(_service.GetBooks());
        }

        public ActionResult Details(int? id)
        {
            Book item = new Book();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            item = _service.GetBook((int)id);
            ViewData["ActionType"] = "Details";
            if (item == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Views/Books/_View.cshtml", item);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    item.BookUserId = UserId;
                    if (_service.AddBook(item) != 0)
                    {
                        ModelSuccess = Resources.Site.MsgSuccess;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        AddModelError(Resources.Site.MsgGeneralError);
                    }
                }
            }
            catch
            {
            }
            return View(item);
        }

        public ActionResult Edit(int? id)
        {
            Book item = new Book();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                item = _service.GetBook((int)id);
                if (item == null)
                {
                    return HttpNotFound();
                }
            }
            catch (Exception ex)
            {
                //Logger.Exception(ex);
                //ModelState.AddModelError("", AppSettingHelper.IsDebugMode ? ex.ToString() : General.Err_TryLater);
            }
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    item.BookUserId = UserId;
                    if (_service.EditBook(item) != 0)
                    {
                        ModelSuccess = Resources.Site.MsgSuccess;
                        return RedirectToAction("Index");
                    }
                }
            }
            catch
            {
                
            }
            return View(item);
        }

        
        public ActionResult Delete(int? id)
        {
            Book item = new Book();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                item = _service.GetBook((int)id);
                if (item == null)
                {
                    return HttpNotFound();
                }
                 ViewData["ActionType"] = "Delete";
            }
            catch (Exception ex)
            {
                //Logger.Exception(ex);
                //ModelState.AddModelError("", AppSettingHelper.IsDebugMode? ex.ToString() : General.Err_TryLater);
            }
            return PartialView("~/Views/Books/_View.cshtml", item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                if (_service.DeleteBook(id, UserId) != 0)
                    ModelSuccess = Resources.Site.MsgSuccess;
                else
                    AddModelError(Resources.Site.MsgGeneralError);
            }
            catch
            {
            }
            return RedirectToAction("Index");
        }
    }
}

OneCard.MVC/Controllers/OwnersController.cs
using SmartMvc.Core.Domain;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OneCard.MVC.Controllers
{
    public class OwnersController : GlobalController
    { 
        public ActionResult Index()
        {
            AddModelSuccess();
            return View(_service.GetOwners());
        }

        public ActionResult Details(int? id)
        {
            Owner item = new Owner();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            item = _service.GetOwner((int)id);
            ViewData["ActionType"] = "Details";
            if (item == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Views/Owners/_View.cshtml", item);
        }
        public ActionResult Create()
        {
            ViewBag.CategoryTypeId = new SelectList(_service.GetCategoryTypes(), "CtId", "CtTitle");
            ViewBag.OwnerTemplateId = new SelectList(_service.GetTemplates(), "TempId", "TempTitle");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Owner item, HttpPostedFileBase OwnerImagePath, HttpPostedFileBase OwnerAttachFile1, HttpPostedFileBase OwnerAttachFile2, HttpPostedFileBase OwnerAttachFile3, string imageData)
        {
            try
            {
                if (OwnerImagePath != null || imageData != null )
                {
                    long milliseconds = DateTimeOffset.Now.ToUnixTimeMilliseconds();
                    if (imageData != null && imageData !="")
                    {
                        string ImageName4 = milliseconds.ToString() + "__Captured";
                        var t = imageData.Substring(22);  // remove data:image/png;base64,  
                        byte[] bytes = Convert.FromBase64String(t);
                        Image image;
                        using (MemoryStream ms = new MemoryStream(bytes))
                        {
                            image = Image.FromStream(ms);
                        }
                        var randomFileName = ImageName4 + ".png";
                        var fullPath = Path.Combine(Server.MapPath("~/Images/"), randomFileName);
                        image.Save(fullPath, System.Drawing.Imaging.ImageFormat.Png);
                        item.OwnerImagePath = randomFileName;
                    }
                    else if (OwnerImagePath != null)
                    {
                        if (Path.GetExtension(OwnerImagePath.FileName).ToLower() == ".jpg" ||
                       Path.GetExtension(OwnerImagePath.FileName).ToLower() == ".png" ||
                       Path.GetExtension(OwnerImagePath.FileName).ToLower() == ".gif" ||
                       Path.GetExtension(OwnerImagePath.FileName).ToLower() == ".jpeg")
                        {
                            string ImageName = milliseconds.ToString() + "__" + System.IO.Path.GetFileName(OwnerImagePath.FileName);
                            string PhysicalPath = Server.MapPath("~/Images/" + ImageName);
                            OwnerImagePath.SaveAs(PhysicalPath);
                            item.OwnerImagePath = ImageName;
                        }
                        else
                        {
                            AddModelError(Resources.Site.MsgAddOwnerExtension);
                            ViewBag.CategoryTypeId = new SelectList(_service.GetCategoryTypes(), "CtId", "CtTitle");
                            ViewBag.OwnerTemplateId = new SelectList(_service.GetTemplates(), "TempId", "TempTitle");
                            return View(item);
                        }
                    }
                    item.OwnerUserId = UserId;
                    item.OwnerModifyUserId = UserId;
                    if (OwnerAttachFile1 != null)
                    {
                        string ImageName1 = milliseconds.ToString() + "__" + System.IO.Path.GetFileName(OwnerAttachFile1.FileName);
                        string PhysicalPath1 = Server.MapPath("~/Files/" + ImageName1);
                        OwnerAttachFile1.SaveAs(PhysicalPath1);
                        item.OwnerAttachFile1 = ImageName1;
                    }
                    if (OwnerAttachFile2 != null)
                    {
                        string ImageName2 = milliseconds.ToString() + "__" + System.IO.Path.GetFileName(OwnerAttachFile2.FileName);
                        string PhysicalPath2 = Server.MapPath("~/Files/" + ImageName2);
                        OwnerAttachFile2.SaveAs(PhysicalPath2);
                        item.OwnerAttachFile2 = ImageName2;
                    }
                    if (OwnerAttachFile3 != null)
                    {
                        string ImageName3 = milliseconds.ToString() + "__" + System.IO.Path.GetFileName(OwnerAttachFile3.FileName);
                        string PhysicalPath3 = Server.MapPath("~/Files/" + ImageName3);
                        OwnerAttachFile3.SaveAs(PhysicalPath3);
                        item.OwnerAttachFile3 = ImageName3;
                    }
                    if (ModelState.IsValid)
                    {
                        AddModelSuccess();
                        if (_service.AddOwner(item) != 0)
                        {
                            ModelSuccess = Resources.Site.MsgSuccess;
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            AddModelError(Resources.Site.MsgGeneralError);
                        }
                    }
                }
                else
                {
                    AddModelError(Resources.Site.MsgAddOwnerImage);
                }

            }
            catch (Exception ex)
            {
                AddModelError(Resources.Site.MsgGeneralError);
            }
            ViewBag.CategoryTypeId = new SelectList(_service.GetCategoryTypes(), "CtId", "CtTitle");
            ViewBag.OwnerTemplateId = new SelectList(_service.GetTemplates(), "TempId", "TempTitle");
            return View(item);
        }

        public ActionResult Edit(int? id)
        {
            Owner item = new Owner();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                item = _service.GetOwner((int)id);
                if (item == null)
                {
                    return HttpNotFound();
                }
                ViewBag.CategoryTypeId = new SelectList(_service.GetCategoryTypes(), "CtId", "CtTitle", item.CategoryTypeId);
                ViewBag.OwnerTemplateId = new SelectList(_service.GetTemplates(), "TempId", "TempTitle", item.OwnerTemplateId);
            }
            catch (Exception ex)
            {
                //Logger.Exception(ex);
                //ModelState.AddModelError("", AppSettingHelper.IsDebugMode ? ex.ToString() : General.Err_TryLater);
            }
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Owner item, HttpPostedFileBase OwnerImagePath, HttpPostedFileBase OwnerAttachFile1, HttpPostedFileBase OwnerAttachFile2, HttpPostedFileBase OwnerAttachFile3, string imageData)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    long milliseconds = DateTimeOffset.Now.ToUnixTimeMilliseconds();
                    if (OwnerImagePath != null || imageData != null)
                    {
                        if (imageData != null && imageData != "")
                        {
                            string ImageName4 = milliseconds.ToString() + "__Captured";
                            var t = imageData.Substring(22);  // remove data:image/png;base64,  
                            byte[] bytes = Convert.FromBase64String(t);
                            Image image;
                            using (MemoryStream ms = new MemoryStream(bytes))
                            {
                                image = Image.FromStream(ms);
                            }
                            var randomFileName = ImageName4 + ".png";
                            var fullPath = Path.Combine(Server.MapPath("~/Images/"), randomFileName);
                            image.Save(fullPath, System.Drawing.Imaging.ImageFormat.Png);
                            item.OwnerImagePath = randomFileName;
                        }
                        else if (OwnerImagePath != null)
                        {
                            if (Path.GetExtension(OwnerImagePath.FileName).ToLower() == ".jpg" ||
                               Path.GetExtension(OwnerImagePath.FileName).ToLower() == ".png" ||
                               Path.GetExtension(OwnerImagePath.FileName).ToLower() == ".gif" ||
                               Path.GetExtension(OwnerImagePath.FileName).ToLower() == ".jpeg")
                            {

                                string ImageName = milliseconds.ToString() + "__" + System.IO.Path.GetFileName(OwnerImagePath.FileName);
                                string PhysicalPath = Server.MapPath("~/Images/" + ImageName);
                                OwnerImagePath.SaveAs(PhysicalPath);
                                item.OwnerImagePath = ImageName;
                            }
                            else
                            {
                                AddModelError(Resources.Site.MsgAddOwnerExtension);
                                ViewBag.CategoryTypeId = new SelectList(_service.GetCategoryTypes(), "CtId", "CtTitle", item.CategoryTypeId);

OneCard.MVC/Views/Shared/_Layout.cshtml
@using OneCard.MVC.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @if (ViewBag.Titel != null)
    {
        <title>@Resources.Site.AppName - @ViewBag.Titel</title>
    }
    else
    {
        <title>@Resources.Site.AppName</title>
    }

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @if (CultureHelper.IsRtl)
    {
        @Styles.Render("~/Content/InternalStylesAr")
    }

    @RenderSection("styles", required: false)

</head>
<body>

    @*@Html.Partial("_NavBar")*@
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(Resources.Site.AppName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Resources.Site.HomePage, "Index", "Home")</li>
                    <li>@Html.ActionLink(Resources.Site.CategoryTypes, "Index", "CategoryTypes")</li>
                    <li>@Html.ActionLink(Resources.Site.Library, "Index", "Books")</li>
                    <li>@Html.ActionLink(Resources.Site.Terminals, "Index", "Terminals")</li>
                    <li>@Html.ActionLink(Resources.Site.FoodMenu, "Index", "FoodMenus")</li>
                    <li>@Html.ActionLink(Resources.Site.Templates, "Index", "Templates")</li>
                    <li>@Html.ActionLink(Resources.Site.Owners, "Index", "Owners")</li>
                    <li class="lang-btn">
                        @if (CultureHelper.IsRtl)
                        {
                            <a href="@Url.Action("ChangeSessionCulture", "Home", new { cultureName = Resources.Site.LangaugeCode })" class="Item" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="lang-icon">
                                    <img src="~/Content/images/gb.png" />
                                </span>
                            </a>
                        }
                        else
                        {
                            <a href="@Url.Action("ChangeSessionCulture", "Home", new { cultureName = Resources.Site.LangaugeCode })" class="Item" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="lang-icon">
                                    <img src="~/Content/images/sa.png" />
                                </span>
                            </a>
                        }
                    </li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="page-content-wrap">
            @RenderBody()

        </div>
        @*<hr />*@
        <footer>
            <p>&copy; @DateTime.Now.Year - @Resources.Site.AppName</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    
    @if (CultureHelper.IsRtl)
    {
        // @Scripts.Render("~/bundles/InternalScriptsAr")
    }
    <div class="modal" id="popup_container" tabindex="-1" role="dialog" aria-labelledby="defModalHead" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">@Resources.Site.Close</span></button>
                    <h4 class="modal-title" id="defModalHead"></h4>
                </div>
                <div class="modal-body" style="text-align:center;">
                    <img src="/Content/images/loader.gif" alt="Loading ..." style="margin-left:auto; margin-right:auto; margin-top:100px; margin-bottom:100px; width:75px;" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">@Resources.Site.Close</button>
                </div>
            </div>
        </div>
    </div>


    <div class="modal" id="confirm_container" tabindex="-1" role="dialog" aria-labelledby="defModalHead" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">@Resources.Site.Close</span></button>
                    <h4 class="modal-title" id="defModalHead"></h4>
                </div>
                <div class="modal-body" style="text-align:center;">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">@Resources.Site.Close</button>
                    <button type="button" id="btnConfirmApprove" class="btn btn-primary" data-dismiss="modal">@Resources.Site.Confirm</button>
                </div>
            </div>
        </div>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

OneCard.MVC/Views/Shared/_MessageResult.cshtml
@using OneCard.MVC.Helpers

@if (ViewData != null)
{


    if (ViewData[MsgHelper.ModelInfo] != null)
    {
        <div class="alert alert-info" role="alert">
            <strong> @*@Resources.Site.Success*@  </strong> @ViewData[MsgHelper.ModelInfo]
        </div>
    }


    if (!ViewData.ModelState.IsValid)
    {
        if (ViewData.ModelState[MsgHelper.ModelError] != null)
        {
            foreach (var error in ViewData.ModelState[MsgHelper.ModelError].Errors)
            {
                <div class="alert alert-danger" role="alert">
                    <strong>@Resources.Site.Error</strong> @error.ErrorMessage
                </div>
            }
        }

    }
    else
    {
        if (ViewData[MsgHelper.ModelSuccess] != null)
        {
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">@Resources.Site.Close</span></button>
                <strong>@Resources.Site.Success</strong> @ViewData[MsgHelper.ModelSuccess]
            </div>
        }
       


    }
}

OneCard.MVC/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink(Resources.Site.AppName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink(Resources.Site.HomePage, "Index", "Home")</li>
                <li>@Html.ActionLink(Resources.Site.CategoryTypes, "Index", "CategoryTypes")</li>
                @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
            </ul>
            @*@Html.Partial("_LoginPartial")*@
        </div>
    </div>
</div>
@*<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>*@