OneCard.MVC/Controllers/FoodMenusController.cs
using SmartMvc.Core.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OneCard.MVC.Controllers
{
    public class FoodMenusController : GlobalController
    {
        public ActionResult Index()
        {
            AddModelSuccess();
            return View(_service.GetFoodMenus());
        }

        public ActionResult Details(int? id)
        {
            FoodMenu item = new FoodMenu();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            item = _service.GetFoodMenu((int)id);
            ViewData["ActionType"] = "Details";
            if (item == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Views/FoodMenus/_View.cshtml", item);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FoodMenu item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    item.FMenuUserId = UserId;
                    item.FMenuModifyUserId = UserId;
                    if (_service.AddFoodMenu(item) != 0)
                    {
                        ModelSuccess = Resources.Site.MsgSuccess;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        AddModelError(Resources.Site.MsgGeneralError);
                    }
                }
            }
            catch
            {
            }
            return View(item);
        }

        public ActionResult Edit(int? id)
        {
            FoodMenu item = new FoodMenu();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                item = _service.GetFoodMenu((int)id);
                if (item == null)
                {
                    return HttpNotFound();
                }
            }
            catch (Exception ex)
            {
                //Logger.Exception(ex);
                //ModelState.AddModelError("", AppSettingHelper.IsDebugMode ? ex.ToString() : General.Err_TryLater);
            }
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FoodMenu item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    item.FMenuModifyUserId = UserId;
                    if (_service.EditFoodMenu(item) != 0)
                    {
                        ModelSuccess = Resources.Site.MsgSuccess;
                        return RedirectToAction("Index");
                    }
                }
            }
            catch
            {

            }
            return View(item);
        }

        public ActionResult Delete(int? id)
        {
            FoodMenu item = new FoodMenu();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                item = _service.GetFoodMenu((int)id);
                if (item == null)
                {
                    return HttpNotFound();
                }
                ViewData["ActionType"] = "Delete";
            }
            catch (Exception ex)
            {
                //Logger.Exception(ex);
                //ModelState.AddModelError("", AppSettingHelper.IsDebugMode? ex.ToString() : General.Err_TryLater);
            }
            return PartialView("~/Views/FoodMenus/_View.cshtml", item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                if (_service.DeleteFoodMenu(id, UserId) != 0)
                    ModelSuccess = Resources.Site.MsgSuccess;
                else
                    AddModelError(Resources.Site.MsgGeneralError);
            }
            catch
            {
            }
            return RedirectToAction("Index");
        }
    }
}

OneCard.MVC/Views/FoodMenus/Create.cshtml
@model SmartMvc.Core.Domain.FoodMenu

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-md-12">
    <div class="form-manage">

        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "CreateForm" }))
        {
            @Html.AntiForgeryToken()
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="fa fa-plus"></span> @String.Format("{0}", Resources.Site.AddFoodMenu)
                </h3>
            </div>
            <div class="panel-body">
                <div class="">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.Partial("~/Views/Shared/_MessageResult.cshtml", ViewData)
                    <div class="form-group">
                        @Html.LabelFor(model => model.FMenuCode, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.FMenuCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FMenuCode, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FMenuTitle, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.FMenuTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FMenuTitle, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FMenuDescription, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.FMenuDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FMenuDescription, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FMenuPrice, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.FMenuPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FMenuPrice, "", new { @class = "text-danger" })

                    </div>

                    @*<div class="form-group">
            @Html.LabelFor(model => model.FMenuAddDate, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FMenuAddDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FMenuAddDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FMenuModifyDate, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FMenuModifyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FMenuModifyDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    @*<div class="form-group">
            @Html.LabelFor(model => model.FMenuUserId, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FMenuUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FMenuUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FMenuModifyUserId, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FMenuModifyUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FMenuModifyUserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.FMenuPriority, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.FMenuPriority, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FMenuPriority, "", new { @class = "text-danger" })

                    </div>

                    @*<div class="form-group">
            @Html.LabelFor(model => model.FMenuIsDeleted, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.FMenuIsDeleted)
                    @Html.ValidationMessageFor(model => model.FMenuIsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FMenuIsPublished, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.FMenuIsPublished)
                    @Html.ValidationMessageFor(model => model.FMenuIsPublished, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

                    <div class="form-group">
                        <input type="submit" value='@Resources.Site.Save' class="btn btn-info" />
                        @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
                    </div>
                </div>
            </div>
            </div>
            }
        </div>
        </div>
@section scripts
    {
        @Scripts.Render("~/bundles/jqueryval")
    }

OneCard.MVC/Views/FoodMenus/Edit.cshtml
@model SmartMvc.Core.Domain.FoodMenu

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="col-md-12">
    <div class="form-manage">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "CreateForm" }))
        {
            @Html.AntiForgeryToken()
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="fa fa-edit"></span> @String.Format("{0}", Resources.Site.Edit)
                    :  @Html.DisplayFor(model => model.FMenuTitle)
                </h3>
            </div>
            <div class="panel-body">
                <div class="">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.Partial("~/Views/Shared/_MessageResult.cshtml", ViewData)
                    @Html.HiddenFor(model => model.FMenuId)

                    <div class="form-group">
                        @Html.LabelFor(model => model.FMenuCode, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.FMenuCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FMenuCode, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FMenuTitle, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.FMenuTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FMenuTitle, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FMenuDescription, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.FMenuDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FMenuDescription, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FMenuPrice, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.FMenuPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FMenuPrice, "", new { @class = "text-danger" })

                    </div>

                    @*<div class="form-group">
            @Html.LabelFor(model => model.FMenuAddDate, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FMenuAddDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FMenuAddDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FMenuModifyDate, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FMenuModifyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FMenuModifyDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FMenuUserId, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FMenuUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FMenuUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FMenuModifyUserId, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FMenuModifyUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FMenuModifyUserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.FMenuPriority, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.FMenuPriority, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FMenuPriority, "", new { @class = "text-danger" })

                    </div>

                    @*<div class="form-group">
            @Html.LabelFor(model => model.FMenuIsDeleted, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.FMenuIsDeleted)
                    @Html.ValidationMessageFor(model => model.FMenuIsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FMenuIsPublished, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.FMenuIsPublished)
                    @Html.ValidationMessageFor(model => model.FMenuIsPublished, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value='@Resources.Site.Save' class="btn btn-info" />
                            @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
                        </div>
                    </div>
                </div>
            </div>
            </div>
            }
        </div>
        </div>
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

OneCard.MVC/Views/FoodMenus/Index.cshtml
@model IEnumerable<SmartMvc.Core.Domain.FoodMenu>
@using OneCard.MVC.Helpers

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel-heading">
            <h2>@Resources.Site.FoodMenu</h2>
            <div class="create-btn">
                @Html.ActionLink(@Resources.Site.AddFoodMenu, "Create", null, new { @class = "btn btn-info" })
            </div>
        </div>

        <div class="panel-body">
            @Html.Partial("~/Views/Shared/_MessageResult.cshtml", ViewData)
            <div id="TableList">
                <table class="table datatable">
                    <thead>
                        <tr>
                            <th>
                                @Resources.Site.RowNo
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FMenuCode)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FMenuTitle)
                            </th>
                            @*<th>
                                @Html.DisplayNameFor(model => model.FMenuDescription)
                            </th>*@
                            <th>
                                @Html.DisplayNameFor(model => model.FMenuPrice)
                            </th>
                            @*<th>
                                @Html.DisplayNameFor(model => model.FMenuAddDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FMenuModifyDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FMenuUserId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FMenuModifyUserId)
                            </th>*@
                            <th>
                                @Html.DisplayNameFor(model => model.FMenuPriority)
                            </th>
                            @*<th>
                                @Html.DisplayNameFor(model => model.FMenuIsDeleted)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FMenuIsPublished)
                            </th>*@
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int rowNo = 0; }
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @(rowNo += 1)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FMenuCode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FMenuTitle)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.FMenuDescription)
                            </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.FMenuPrice)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.FMenuAddDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FMenuModifyDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FMenuUserId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FMenuModifyUserId)
                            </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.FMenuPriority)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.FMenuIsDeleted)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FMenuIsPublished)
                            </td>*@
                            <td>
                                @Html.ActionLink(@Resources.Site.Edit, "Edit", new { id = item.FMenuId }, new { @class = "btn btn-info  fa fa-edit" })
                                <a href="#" onclick="showPopup('@Url.Action("Delete", "FoodMenus",  new { id = item.FMenuId })', '@String.Format("{0}",item.FMenuTitle) ')"
                                   title='@Resources.Site.Delete' class="btn btn-danger fa fa-trash-o">@Resources.Site.Delete</a>
                                <a href="#" onclick="showPopup('@Url.Action("Details", "FoodMenus",  new { id = item.FMenuId })', '@String.Format("{0}",item.FMenuTitle) ')"
                                   title='@Resources.Site.Details' class="btn btn-default">@Resources.Site.Details</a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
            </div>
        </div>
    </div>


@section scripts
{
    @if (CultureHelper.IsRtl)
    {
        <script>
            var lang = 'ar';
            initDatatable(lang);
        </script>
    }
    else
    {
        <script>
            var lang = 'en';
            initDatatable(lang);
        </script>
    }
}

OneCard.MVC/Views/FoodMenus/_View.cshtml
@model SmartMvc.Core.Domain.FoodMenu

@{
    string actionType = (string)ViewData["ActionType"];
}

@if (@actionType == "Delete")
{
    <div class="alert alert-danger" role="alert">
        <strong>@Resources.Site.Attention</strong> @Resources.Site.ConfirmDeleting
    </div>
}
    <div class="clear"></div>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FMenuCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FMenuCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FMenuTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FMenuTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FMenuDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FMenuDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FMenuPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FMenuPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FMenuAddDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FMenuAddDate)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.FMenuModifyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FMenuModifyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FMenuUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FMenuUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FMenuModifyUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FMenuModifyUserId)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.FMenuPriority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FMenuPriority)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.FMenuIsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FMenuIsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FMenuIsPublished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FMenuIsPublished)
        </dd>*@

    </dl>
</div>
<div>

    @if (@actionType == "Delete")
    {
        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="submit" value='@Resources.Site.Delete' class="btn btn-danger" />
                @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
            </div>
        }
    }
    else
    {
        <p>
            @Html.ActionLink(Resources.Site.Edit, "Edit", new { id = Model.FMenuId }, new { @class = "btn btn-info" })
            @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
        </p>
    }
</div>