OneCard.MVC/Controllers/TerminalsController.cs
using SmartMvc.Core.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OneCard.MVC.Controllers
{
    public class TerminalsController : GlobalController
    {
        public ActionResult Index()
        {
            AddModelSuccess();
            return View(_service.GetTerminals());
        }
        public ActionResult Details(int? id)
        {
            Terminal item = new Terminal();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            item = _service.GetTerminal((int)id);
            ViewData["ActionType"] = "Details";
            if (item == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Views/Terminals/_View.cshtml", item);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Terminal item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    item.TermUserId = UserId;
                    item.TermModifyUserId = UserId;
                    if (_service.AddTerminal(item) != 0)
                    {
                        ModelSuccess = Resources.Site.MsgSuccess;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        AddModelError(Resources.Site.MsgGeneralError);
                    }
                }
            }
            catch
            {
            }
            return View(item);
        }

        public ActionResult Edit(int? id)
        {
            Terminal item = new Terminal();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                item = _service.GetTerminal((int)id);
                if (item == null)
                {
                    return HttpNotFound();
                }
            }
            catch (Exception ex)
            {
                //Logger.Exception(ex);
                //ModelState.AddModelError("", AppSettingHelper.IsDebugMode ? ex.ToString() : General.Err_TryLater);
            }
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Terminal item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    item.TermModifyUserId = UserId;
                    if (_service.EditTerminal(item) != 0)
                    {
                        ModelSuccess = Resources.Site.MsgSuccess;
                        return RedirectToAction("Index");
                    }
                }
            }
            catch
            {

            }
            return View(item);
        }

        public ActionResult Delete(int? id)
        {
            Terminal item = new Terminal();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                item = _service.GetTerminal((int)id);
                if (item == null)
                {
                    return HttpNotFound();
                }
                ViewData["ActionType"] = "Delete";
            }
            catch (Exception ex)
            {
                //Logger.Exception(ex);
                //ModelState.AddModelError("", AppSettingHelper.IsDebugMode? ex.ToString() : General.Err_TryLater);
            }
            return PartialView("~/Views/Terminals/_View.cshtml", item);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                if (_service.DeleteTerminal(id, UserId) != 0)
                    ModelSuccess = Resources.Site.MsgSuccess;
                else
                    AddModelError(Resources.Site.MsgGeneralError);
            }
            catch
            {
            }
            return RedirectToAction("Index");
        }
    }
}

OneCard.MVC/Views/Terminals/Create.cshtml
@model SmartMvc.Core.Domain.Terminal

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="form-manage">

        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "CreateForm" }))
        {
            @Html.AntiForgeryToken()
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="fa fa-plus"></span> @String.Format("{0}", Resources.Site.AddTerminal)
                </h3>
            </div>
            <div class="panel-body">
                <div class="">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.Partial("~/Views/Shared/_MessageResult.cshtml", ViewData)
                    <div class="form-group">
                        @Html.LabelFor(model => model.TermCode, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.TermCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TermCode, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TermTitle, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.TermTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TermTitle, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TermDescription, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.TermDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TermDescription, "", new { @class = "text-danger" })

                    </div>

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermAddDate, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TermAddDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TermAddDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermModifyDate, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TermModifyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TermModifyDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermUserId, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TermUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TermUserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermModifyUserId, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TermModifyUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TermModifyUserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.TermPriority, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.TermPriority, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TermPriority, "", new { @class = "text-danger" })

                    </div>

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermIsDeleted, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TermIsDeleted)
                    @Html.ValidationMessageFor(model => model.TermIsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermIsPublished, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TermIsPublished)
                    @Html.ValidationMessageFor(model => model.TermIsPublished, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@
                    <div class="form-group">
                        <input type="submit" value='@Resources.Site.Save' class="btn btn-info" />
                        @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
                    </div>
                </div>
            </div>
            </div>
        }
        </div>
</div>
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

OneCard.MVC/Views/Terminals/Edit.cshtml
@model SmartMvc.Core.Domain.Terminal

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12">
    <div class="form-manage">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "CreateForm" }))
        {
            @Html.AntiForgeryToken()
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="fa fa-edit"></span> @String.Format("{0}", Resources.Site.Edit)
                    :  @Html.DisplayFor(model => model.TermTitle)
                </h3>
            </div>
            <div class="panel-body">
                <div class="">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.Partial("~/Views/Shared/_MessageResult.cshtml", ViewData)
                    @Html.HiddenFor(model => model.TermId)

                    <div class="form-group">
                        @Html.LabelFor(model => model.TermCode, htmlAttributes: new { @class = "control-label " })

                        @Html.EditorFor(model => model.TermCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TermCode, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TermTitle, htmlAttributes: new { @class = "control-label " })

                        @Html.EditorFor(model => model.TermTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TermTitle, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TermDescription, htmlAttributes: new { @class = "control-label " })

                        @Html.EditorFor(model => model.TermDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TermDescription, "", new { @class = "text-danger" })

                    </div>

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermAddDate, htmlAttributes: new { @class = "control-label " })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TermAddDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TermAddDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermModifyDate, htmlAttributes: new { @class = "control-label " })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TermModifyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TermModifyDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermUserId, htmlAttributes: new { @class = "control-label " })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TermUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TermUserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermModifyUserId, htmlAttributes: new { @class = "control-label " })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TermModifyUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TermModifyUserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.TermPriority, htmlAttributes: new { @class = "control-label " })

                        @Html.EditorFor(model => model.TermPriority, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TermPriority, "", new { @class = "text-danger" })

                    </div>

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermIsDeleted, htmlAttributes: new { @class = "control-label " })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TermIsDeleted)
                    @Html.ValidationMessageFor(model => model.TermIsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TermIsPublished, htmlAttributes: new { @class = "control-label " })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TermIsPublished)
                    @Html.ValidationMessageFor(model => model.TermIsPublished, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value='@Resources.Site.Save' class="btn btn-info" />
                            @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        }
     </div>
</div>
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

OneCard.MVC/Views/Terminals/Index.cshtml
@model IEnumerable<SmartMvc.Core.Domain.Terminal>
@using OneCard.MVC.Helpers
@{
    ViewBag.Title = @Resources.Site.Terminal;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel-heading">
            <h2>@Resources.Site.Terminals</h2>
            <div class="create-btn">
                @Html.ActionLink(@Resources.Site.AddTerminal, "Create", null, new { @class = "btn btn-info" })
            </div>
        </div>

        <div class="panel-body">
            @Html.Partial("~/Views/Shared/_MessageResult.cshtml", ViewData)
            <div id="TableList">
                <table class="table datatable">
                    <thead>
                        <tr>
                            <th>
                                @Resources.Site.RowNo
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TermCode)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TermTitle)
                            </th>
                            @*<th>
                                    @Html.DisplayNameFor(model => model.TermDescription)
                                </th>*@
                            <th>
                                @Html.DisplayNameFor(model => model.TermAddDate)
                            </th>
                            @*<th>
                                    @Html.DisplayNameFor(model => model.TermModifyDate)
                                </th>*@
                            @*<th>
                                    @Html.DisplayNameFor(model => model.TermUserId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.TermModifyUserId)
                                </th>*@
                            <th>
                                @Html.DisplayNameFor(model => model.TermPriority)
                            </th>
                            @*<th>
                                    @Html.DisplayNameFor(model => model.TermIsDeleted)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.TermIsPublished)
                                </th>*@
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int rowNo = 0; }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @(rowNo += 1)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TermCode)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TermTitle)
                                </td>
                                @*<td>
                                        @Html.DisplayFor(modelItem => item.TermDescription)
                                    </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.TermAddDate)
                                </td>
                                @*<td>
                                        @Html.DisplayFor(modelItem => item.TermModifyDate)
                                    </td>*@
                                @*<td>
                                        @Html.DisplayFor(modelItem => item.TermUserId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TermModifyUserId)
                                    </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.TermPriority)
                                </td>
                                @*<td>
                                        @Html.DisplayFor(modelItem => item.TermIsDeleted)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TermIsPublished)
                                    </td>*@
                                <td>
                                    @Html.ActionLink(@Resources.Site.Edit, "Edit", new { id = item.TermId }, new { @class = "btn btn-info  fa fa-edit" })
                                    <a href="#" onclick="showPopup('@Url.Action("Delete", "Terminals",  new { id = item.TermId })', '@String.Format("{0}",item.TermTitle) ')"
                                       title='@Resources.Site.Delete' class="btn btn-danger fa fa-trash-o">@Resources.Site.Delete</a>
                                    <a href="#" onclick="showPopup('@Url.Action("Details", "Terminals",  new { id = item.TermId })', '@String.Format("{0}",item.TermTitle) ')"
                                       title='@Resources.Site.Details' class="btn btn-default">@Resources.Site.Details</a>


                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


@section scripts
{
    @if (CultureHelper.IsRtl)
    {
        <script>
            var lang = 'ar';
            initDatatable(lang);
        </script>
    }
    else
    {
        <script>
            var lang = 'en';
            initDatatable(lang);
        </script>
    }
}

OneCard.MVC/Views/Terminals/_View.cshtml
@model SmartMvc.Core.Domain.Terminal

@{
    string actionType = (string)ViewData["ActionType"];
}

@if (@actionType == "Delete")
{
    <div class="alert alert-danger" role="alert">
        <strong>@Resources.Site.Attention</strong> @Resources.Site.ConfirmDeleting
    </div>
}
<div class="clear"></div>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TermCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TermCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TermTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TermTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TermDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TermDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TermAddDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TermAddDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TermModifyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TermModifyDate)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.TermUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TermUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TermModifyUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TermModifyUserId)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.TermPriority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TermPriority)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.TermIsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TermIsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TermIsPublished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TermIsPublished)
        </dd>*@

    </dl>

</div>
<div>

    @if (@actionType == "Delete")
    {
        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="submit" value='@Resources.Site.Delete' class="btn btn-danger" />
                @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
            </div>
        }
    }
    else
    {
        <p>
            @Html.ActionLink(Resources.Site.Edit, "Edit", new { id = Model.TermId }, new { @class = "btn btn-info" })
            @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
        </p>
    }
</div>