OneCard.MVC/Controllers/TemplatesController.cs
using SmartMvc.Core.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OneCard.MVC.Controllers
{
    public class TemplatesController : GlobalController
    {
        public ActionResult Index()
        {
            AddModelSuccess();
            return View(_service.GetTemplates());
        }

        public ActionResult Details(int? id)
        {
            Template item = new Template();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            item = _service.GetTemplate((int)id);
            ViewData["ActionType"] = "Details";
            if (item == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Views/Templates/_View.cshtml", item);
        }

        public ActionResult Create()
        {
            ViewBag.CategoryTypeId = new SelectList(_service.GetCategoryTypes(), "CtId", "CtTitle"); 

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Template item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    item.TempUserId = UserId;
                    item.TempModifyUserId = UserId;
                    if (_service.AddTemplate(item) != 0)
                    {
                        ModelSuccess = Resources.Site.MsgSuccess;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        AddModelError(Resources.Site.MsgGeneralError);
                    }
                }
                ViewBag.CategoryTypeId = new SelectList(_service.GetCategoryTypes(), "CtId", "CtTitle"); 
            }
            catch
            {
            }
            return View(item);
        }

        public ActionResult Edit(int? id)
        {
            Template item = new Template();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                item = _service.GetTemplate((int)id);
                if (item == null)
                {
                    return HttpNotFound();
                }
                ViewBag.CategoryTypeId = new SelectList(_service.GetCategoryTypes(), "CtId", "CtTitle", item.CategoryTypeId); 
            }
            catch (Exception ex)
            {
                //Logger.Exception(ex);
                //ModelState.AddModelError("", AppSettingHelper.IsDebugMode ? ex.ToString() : General.Err_TryLater);
            }
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Template item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    item.TempModifyUserId = UserId;
                    if (_service.EditTemplate(item) != 0)
                    {
                        ModelSuccess = Resources.Site.MsgSuccess;
                        return RedirectToAction("Index");
                    }
                }
                ViewBag.CategoryTypeId = new SelectList(_service.GetCategoryTypes(), "CtId", "CtTitle", item.CategoryTypeId); 

            }
            catch
            {

            }
            return View(item);
        }

        public ActionResult Delete(int? id)
        {
            Template item = new Template();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                item = _service.GetTemplate((int)id);
                if (item == null)
                {
                    return HttpNotFound();
                }
                ViewData["ActionType"] = "Delete";
            }
            catch (Exception ex)
            {
                //Logger.Exception(ex);
                //ModelState.AddModelError("", AppSettingHelper.IsDebugMode? ex.ToString() : General.Err_TryLater);
            }
            return PartialView("~/Views/Templates/_View.cshtml", item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                if (_service.DeleteTemplate(id, UserId) != 0)
                    ModelSuccess = Resources.Site.MsgSuccess;
                else
                    AddModelError(Resources.Site.MsgGeneralError);
            }
            catch
            {
            }
            return RedirectToAction("Index");
        }
        public ActionResult SetTemplateDefualt(int? id)
        {
            Template item = new Template();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                item = _service.GetTemplate((int)id);
                if (item == null)
                {
                    return HttpNotFound();
                }
               // ViewData["ActionType"] = "Delete";
            }
            catch (Exception ex)
            {
                //Logger.Exception(ex);
                //ModelState.AddModelError("", AppSettingHelper.IsDebugMode? ex.ToString() : General.Err_TryLater);
            }
            return PartialView("~/Views/Templates/_ConfirmDefualt.cshtml", item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SetTemplateDefualt(int id)
        {
            try
            {
                if (_service.SetTemplateDefualt(id, UserId) != 0)
                    ModelSuccess = Resources.Site.MsgSuccess;
                else
                    AddModelError(Resources.Site.MsgGeneralError);
            }
            catch
            {
            }
            return RedirectToAction("Index");
        }

    }
}

OneCard.MVC/Views/Templates/Create.cshtml
@model SmartMvc.Core.Domain.Template

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="form-manage">

        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "CreateForm" }))
        {
            @Html.AntiForgeryToken()
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="fa fa-plus"></span> @String.Format("{0}", Resources.Site.AddTemplate)
                    </h3>
                </div>
                <div class="panel-body">
                    <div class="">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.Partial("~/Views/Shared/_MessageResult.cshtml", ViewData)
                        <div class="form-group">
                            @Html.LabelFor(model => model.TempCode, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.TempCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TempCode, "", new { @class = "text-danger" })

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.TempTitle, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.TempTitle, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TempTitle, "", new { @class = "text-danger" })

                        </div>

                        @*<div class="form-group">
            @Html.LabelFor(model => model.TempPath, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.TempPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempPath, "", new { @class = "text-danger" })

        </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.TempDescription, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.TempDescription, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TempDescription, "", new { @class = "text-danger" })

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CategoryTypeId, Resources.Site.CategoryType, htmlAttributes: new { @class = "control-label" })
                            @Html.DropDownList("CategoryTypeId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CategoryTypeId, "", new { @class = "text-danger" })

                        </div>

                        @*<div class="form-group">
            @Html.LabelFor(model => model.TempIsDefualt, htmlAttributes: new { @class = "control-label" })

            <div class="checkbox">
                @Html.EditorFor(model => model.TempIsDefualt)
                @Html.ValidationMessageFor(model => model.TempIsDefualt, "", new { @class = "text-danger" })
            </div>

        </div>*@

                        @*<div class="form-group">
            @Html.LabelFor(model => model.TempAddDate, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.TempAddDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempAddDate, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempModifyDate, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.TempModifyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempModifyDate, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempUserId, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.TempUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempUserId, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempModifyUserId, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.TempModifyUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempModifyUserId, "", new { @class = "text-danger" })

        </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.TempPriority, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.TempPriority, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TempPriority, "", new { @class = "text-danger" })

                        </div>

                        @*<div class="form-group">
            @Html.LabelFor(model => model.TempIsDeleted, htmlAttributes: new { @class = "control-label" })

                <div class="checkbox">
                    @Html.EditorFor(model => model.TempIsDeleted)
                    @Html.ValidationMessageFor(model => model.TempIsDeleted, "", new { @class = "text-danger" })
                </div>

        </div>*@

                        @*<div class="form-group">
            @Html.LabelFor(model => model.TempIsPublished, htmlAttributes: new { @class = "control-label" })

                <div class="checkbox">
                    @Html.EditorFor(model => model.TempIsPublished)
                    @Html.ValidationMessageFor(model => model.TempIsPublished, "", new { @class = "text-danger" })
                </div>

        </div>*@

                        <div class="form-group">
                            <input type="submit" value='@Resources.Site.Save' class="btn btn-info" />
                            @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>
@*@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}*@

OneCard.MVC/Views/Templates/Edit.cshtml
@model SmartMvc.Core.Domain.Template

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="form-manage">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "CreateForm" }))
        {
            @Html.AntiForgeryToken()
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="fa fa-edit"></span> @String.Format("{0}", Resources.Site.Edit)
                    :  @Html.DisplayFor(model => model.TempTitle)
                </h3>
            </div>
            <div class="panel-body">
                <div class="">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.Partial("~/Views/Shared/_MessageResult.cshtml", ViewData)
                    @Html.HiddenFor(model => model.TempId)
                    <div class="form-group">
                        @Html.LabelFor(model => model.TempCode, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.TempCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TempCode, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.TempTitle, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.TempTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TempTitle, "", new { @class = "text-danger" })

                    </div>

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TempPath, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.TempPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempPath, "", new { @class = "text-danger" })

        </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.TempDescription, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.TempDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TempDescription, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CategoryTypeId, Resources.Site.CategoryType, htmlAttributes: new { @class = "control-label" })

                        @Html.DropDownList("CategoryTypeId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CategoryTypeId, "", new { @class = "text-danger" })

                    </div>

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TempIsDefualt, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TempIsDefualt)
                    @Html.ValidationMessageFor(model => model.TempIsDefualt, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TempAddDate, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempAddDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempAddDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempModifyDate, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempModifyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempModifyDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempUserId, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempModifyUserId, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempModifyUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempModifyUserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.TempPriority, htmlAttributes: new { @class = "control-label" })

                        @Html.EditorFor(model => model.TempPriority, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TempPriority, "", new { @class = "text-danger" })

                    </div>

                    @*<div class="form-group">
            @Html.LabelFor(model => model.TempIsDeleted, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TempIsDeleted)
                    @Html.ValidationMessageFor(model => model.TempIsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempIsPublished, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TempIsPublished)
                    @Html.ValidationMessageFor(model => model.TempIsPublished, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value='@Resources.Site.Save' class="btn btn-info" />
                            @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
                        </div>
                    </div>
                </div>
            </div>
            </div>
            }
        </div>
        </div>
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

OneCard.MVC/Views/Templates/Index.cshtml
@model IEnumerable<SmartMvc.Core.Domain.Template>
@using OneCard.MVC.Helpers
@{
    ViewBag.Title = @Resources.Site.Templates;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">

        <div class="panel-heading">
            <h2>@Resources.Site.Templates</h2>
            <div class="create-btn">
                @Html.ActionLink(@Resources.Site.AddTemplate, "Create", null, new { @class = "btn btn-info" })
            </div>
        </div>

        <div class="panel-body">
            @Html.Partial("~/Views/Shared/_MessageResult.cshtml", ViewData)
            <div id="TableList">
                <table class="table datatable">
                    <thead>
                        <tr>
                            <th>
                                @Resources.Site.RowNo
                            </th>
                            <th>
                                @Resources.Site.CategoryType
                                @*@Html.DisplayNameFor(model => model.CategoryType.CtId)*@
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TempCode)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TempTitle)
                            </th>
                            @*<th>
                                    @Html.DisplayNameFor(model => model.TempPath)
                                </th>*@
                            @*<th>
                                    @Html.DisplayNameFor(model => model.TempDescription)
                                </th>*@
                            <th>
                                @Html.DisplayNameFor(model => model.TempIsDefualt)
                            </th>
                            @*<th>
                                    @Html.DisplayNameFor(model => model.TempAddDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.TempModifyDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.TempUserId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.TempModifyUserId)
                                </th>*@
                            <th>
                                @Html.DisplayNameFor(model => model.TempPriority)
                            </th>
                            @*<th>
                                    @Html.DisplayNameFor(model => model.TempIsDeleted)
                                </th>*@
                            @*<th>
                                    @Html.DisplayNameFor(model => model.TempIsPublished)
                                </th>*@
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int rowNo = 0; }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @(rowNo += 1)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CategoryType.CtTitle)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TempCode)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TempTitle)
                                </td>
                                @*<td>
                                        @Html.DisplayFor(modelItem => item.TempPath)
                                    </td>*@
                                @*<td>
                                        @Html.DisplayFor(modelItem => item.TempDescription)
                                    </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.TempIsDefualt)
                                </td>
                                @*<td>
                                        @Html.DisplayFor(modelItem => item.TempAddDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TempModifyDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TempUserId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TempModifyUserId)
                                    </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.TempPriority)
                                </td>
                                @*<td>
                                        @Html.DisplayFor(modelItem => item.TempIsDeleted)
                                    </td>*@
                                @*<td>
                                        @Html.DisplayFor(modelItem => item.TempIsPublished)
                                    </td>*@
                                <td>
                                    @Html.ActionLink(@Resources.Site.Edit, "Edit", new { id = item.TempId }, new { @class = "btn btn-info  fa fa-edit" })

                                    <a href="#" onclick="showPopup('@Url.Action("Details", "Templates",  new { id = item.TempId })', '@String.Format("{0}",item.TempTitle) ')"
                                       title='@Resources.Site.Details' class="btn btn-default">@Resources.Site.Details</a>
                                    @if (!item.TempIsDefualt)
                                    {
                                        <a href="#" onclick="showPopup('@Url.Action("Delete", "Templates",  new { id = item.TempId })', '@String.Format("{0}",item.TempTitle) ')"
                                           title='@Resources.Site.Delete' class="btn btn-danger fa fa-trash-o">@Resources.Site.Delete</a>
                                        <a href="#" onclick="showPopup('@Url.Action("SetTemplateDefualt", "Templates",  new { id = item.TempId })', '@String.Format("{0}",item.TempTitle) ')"
                                           title='@Resources.Site.SetAsDefualt' class="btn btn-success">@Resources.Site.SetAsDefualt</a>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    @if (CultureHelper.IsRtl)
    {
        <script>
            var lang = 'ar';
            initDatatable(lang);
        </script>
    }
    else
    {
        <script>
            var lang = 'en';
            initDatatable(lang);
        </script>
    }
}

OneCard.MVC/Views/Templates/_ConfirmDefualt.cshtml
<div>
    <div class="alert alert-info" role="alert">
        @Resources.Site.ConfirmDefualt
    </div>

    <div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="submit" value='@Resources.Site.Confirm' class="btn btn-danger" />
                @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
            </div>
        }
    </div>
</div>

OneCard.MVC/Views/Templates/_View.cshtml
@model SmartMvc.Core.Domain.Template

@{
    string actionType = (string)ViewData["ActionType"];
}

@if (@actionType == "Delete")
{
    <div class="alert alert-danger" role="alert">
        <strong>@Resources.Site.Attention</strong> @Resources.Site.ConfirmDeleting
    </div>
}

<div class="clear"></div>
<div>
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.CategoryType.CtCode)*@
            @Resources.Site.CategoryType
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryType.CtTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempTitle)
        </dd>

        @* <dt>
           @Html.DisplayNameFor(model => model.TempPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempPath)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.TempDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempIsDefualt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempIsDefualt)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.TempAddDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempAddDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempModifyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempModifyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempModifyUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempModifyUserId)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.TempPriority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempPriority)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.TempIsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempIsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempIsPublished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempIsPublished)
        </dd>*@

    </dl>
</div>
<div>

    @if (@actionType == "Delete")
    {
        if (!Model.TempIsDefualt)
        {
            using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <input type="submit" value='@Resources.Site.Delete' class="btn btn-danger" />
                    @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
                </div>
            }
        }
    }
    else
    {
        <p>
            @Html.ActionLink(Resources.Site.Edit, "Edit", new { id = Model.TempId }, new { @class = "btn btn-info" })
            @Html.ActionLink(Resources.Site.BackToList, "Index", null, new { @class = "btn btn-default" })
        </p>
    }
</div>